# Generated by Django 4.0.2 on 2022-02-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_faq_answer_alter_faq_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='user_type',
            field=models.CharField(choices=[('U', 'user'), ('E', 'employee')], default='user', max_length=4),
        ),
    ]
