# Generated by Django 4.0.2 on 2022-02-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_faq_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='priority',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
