# Generated by Django 3.2.11 on 2022-04-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_faq_is_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='user_type',
            field=models.CharField(choices=[('U', 'user'), ('E', 'employee'), ('A', 'app')], default='user', max_length=4),
        ),
    ]
