# Generated by Django 3.2.11 on 2022-04-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0006_alter_faq_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='user_type',
            field=models.CharField(choices=[('U', 'user'), ('E', 'employee'), ('A', 'app'), ('Fatakpay Card', 'Fatakpay Card'), ('Payments', 'Payments'), ('Get Started', 'Get Started')], default='user', max_length=255),
        ),
    ]
