# Generated by Django 4.0.2 on 2022-08-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0010_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='updated_at',
        ),
    ]
