# Generated by Django 4.0.2 on 2022-02-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='linkedin_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
