# Generated by Django 4.0.2 on 2022-02-18 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('work_email', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_loc', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_no', models.IntegerField(blank=True, null=True)),
                ('where_hear', models.CharField(choices=[('Referral', 'Referral'), ('Search_Engine', 'Search_Engine'), ('Another_Website', 'Another_Website'), ('Social_Media', 'Social_Media'), ('WhatsApp', 'WhatsApp'), ('Ad', 'Ad'), ('SMS', 'SMS'), ('Other', 'Other')], default='Other', max_length=100)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Corporate',
                'db_table': 'Corporate',
            },
        ),
    ]
