# Generated by Django 4.0.2 on 2022-02-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporate',
            name='created_by',
        ),
    ]
