# Generated by Django 4.0.2 on 2022-02-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0002_remove_corporate_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDialCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('dial_code', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'CountryDialCode',
                'db_table': 'CountryDialCode',
            },
        ),
    ]
