# Generated by Django 4.0.2 on 2022-02-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0003_countrydialcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporate',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
