# Generated by Django 4.0.2 on 2022-02-22 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/watch_video')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('report_to', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_type', models.CharField(blank=True, max_length=250, null=True)),
                ('priority', models.FloatField(blank=True, null=True)),
                ('expect_from_you', models.TextField(blank=True, null=True)),
                ('ideal_candidate', models.TextField(blank=True, null=True)),
                ('love_working_fpay', models.TextField(blank=True, null=True)),
                ('perks_benefits', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Career_User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Career',
                'db_table': 'Career',
            },
        ),
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('linkedin_link', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='images/resume')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ApplicationForm_Career', to='career.career')),
            ],
            options={
                'verbose_name_plural': 'ApplicationForm',
                'db_table': 'ApplicationForm',
            },
        ),
    ]
