# Generated by Django 4.0.2 on 2022-02-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_career_employee_type_career_expect_from_you_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='priority',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
