# Generated by Django 4.0.2 on 2022-02-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_career_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
