# Generated by Django 4.0.2 on 2022-02-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_signup_delete_singup_alter_testmonials_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
