# Generated by Django 4.0.2 on 2022-08-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_signup_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
