# Generated by Django 4.0.2 on 2022-08-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_alter_watchvideo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=100)),
                ('manager_email', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('number_of_employees', models.IntegerField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
